// Code generated by MockGen. DO NOT EDIT.
// Source: runner.go
//
// Generated by this command:
//
//	mockgen -source=runner.go -destination=mock_linter_test.go -package=lint Linter
//

// Package lint is a generated GoMock package.
package lint

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLinter is a mock of Linter interface.
type MockLinter struct {
	ctrl     *gomock.Controller
	recorder *MockLinterMockRecorder
	isgomock struct{}
}

// MockLinterMockRecorder is the mock recorder for MockLinter.
type MockLinterMockRecorder struct {
	mock *MockLinter
}

// NewMockLinter creates a new mock instance.
func NewMockLinter(ctrl *gomock.Controller) *MockLinter {
	mock := &MockLinter{ctrl: ctrl}
	mock.recorder = &MockLinterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinter) EXPECT() *MockLinterMockRecorder {
	return m.recorder
}

// Available mocks base method.
func (m *MockLinter) Available(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Available", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Available indicates an expected call of Available.
func (mr *MockLinterMockRecorder) Available(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Available", reflect.TypeOf((*MockLinter)(nil).Available), ctx)
}

// Language mocks base method.
func (m *MockLinter) Language() Language {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Language")
	ret0, _ := ret[0].(Language)
	return ret0
}

// Language indicates an expected call of Language.
func (mr *MockLinterMockRecorder) Language() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Language", reflect.TypeOf((*MockLinter)(nil).Language))
}

// Name mocks base method.
func (m *MockLinter) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockLinterMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockLinter)(nil).Name))
}

// Run mocks base method.
func (m *MockLinter) Run(ctx context.Context, projectDir string, files []string) (*Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, projectDir, files)
	ret0, _ := ret[0].(*Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockLinterMockRecorder) Run(ctx, projectDir, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockLinter)(nil).Run), ctx, projectDir, files)
}

// Version mocks base method.
func (m *MockLinter) Version(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Version indicates an expected call of Version.
func (mr *MockLinterMockRecorder) Version(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockLinter)(nil).Version), ctx)
}

// MockTargetSelector is a mock of TargetSelector interface.
type MockTargetSelector struct {
	ctrl     *gomock.Controller
	recorder *MockTargetSelectorMockRecorder
	isgomock struct{}
}

// MockTargetSelectorMockRecorder is the mock recorder for MockTargetSelector.
type MockTargetSelectorMockRecorder struct {
	mock *MockTargetSelector
}

// NewMockTargetSelector creates a new mock instance.
func NewMockTargetSelector(ctrl *gomock.Controller) *MockTargetSelector {
	mock := &MockTargetSelector{ctrl: ctrl}
	mock.recorder = &MockTargetSelectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetSelector) EXPECT() *MockTargetSelectorMockRecorder {
	return m.recorder
}

// TargetKind mocks base method.
func (m *MockTargetSelector) TargetKind() TargetKind {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TargetKind")
	ret0, _ := ret[0].(TargetKind)
	return ret0
}

// TargetKind indicates an expected call of TargetKind.
func (mr *MockTargetSelectorMockRecorder) TargetKind() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TargetKind", reflect.TypeOf((*MockTargetSelector)(nil).TargetKind))
}
