// Code generated by MockGen. DO NOT EDIT.
// Source: scope.go
//
// Generated by this command:
//
//	mockgen -source=scope.go -destination=mock_git_client_test.go -package=scope gitClientInterface
//

// Package scope is a generated GoMock package.
package scope

import (
	reflect "reflect"

	git "github.com/lerianstudio/ring/scripts/codereview/internal/git"
	gomock "go.uber.org/mock/gomock"
)

// MockgitClientInterface is a mock of gitClientInterface interface.
type MockgitClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockgitClientInterfaceMockRecorder
	isgomock struct{}
}

// MockgitClientInterfaceMockRecorder is the mock recorder for MockgitClientInterface.
type MockgitClientInterfaceMockRecorder struct {
	mock *MockgitClientInterface
}

// NewMockgitClientInterface creates a new mock instance.
func NewMockgitClientInterface(ctrl *gomock.Controller) *MockgitClientInterface {
	mock := &MockgitClientInterface{ctrl: ctrl}
	mock.recorder = &MockgitClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgitClientInterface) EXPECT() *MockgitClientInterfaceMockRecorder {
	return m.recorder
}

// FileExistsAtRef mocks base method.
func (m *MockgitClientInterface) FileExistsAtRef(ref, path string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExistsAtRef", ref, path)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExistsAtRef indicates an expected call of FileExistsAtRef.
func (mr *MockgitClientInterfaceMockRecorder) FileExistsAtRef(ref, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExistsAtRef", reflect.TypeOf((*MockgitClientInterface)(nil).FileExistsAtRef), ref, path)
}

// GetAllChangesDiff mocks base method.
func (m *MockgitClientInterface) GetAllChangesDiff() (*git.DiffResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllChangesDiff")
	ret0, _ := ret[0].(*git.DiffResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllChangesDiff indicates an expected call of GetAllChangesDiff.
func (mr *MockgitClientInterfaceMockRecorder) GetAllChangesDiff() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllChangesDiff", reflect.TypeOf((*MockgitClientInterface)(nil).GetAllChangesDiff))
}

// GetDiff mocks base method.
func (m *MockgitClientInterface) GetDiff(baseRef, headRef string) (*git.DiffResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiff", baseRef, headRef)
	ret0, _ := ret[0].(*git.DiffResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiff indicates an expected call of GetDiff.
func (mr *MockgitClientInterfaceMockRecorder) GetDiff(baseRef, headRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiff", reflect.TypeOf((*MockgitClientInterface)(nil).GetDiff), baseRef, headRef)
}

// GetDiffStatsForFiles mocks base method.
func (m *MockgitClientInterface) GetDiffStatsForFiles(baseRef string, files []string) (git.DiffStats, map[string]git.FileStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiffStatsForFiles", baseRef, files)
	ret0, _ := ret[0].(git.DiffStats)
	ret1, _ := ret[1].(map[string]git.FileStats)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDiffStatsForFiles indicates an expected call of GetDiffStatsForFiles.
func (mr *MockgitClientInterfaceMockRecorder) GetDiffStatsForFiles(baseRef, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiffStatsForFiles", reflect.TypeOf((*MockgitClientInterface)(nil).GetDiffStatsForFiles), baseRef, files)
}

// ListUnstagedFiles mocks base method.
func (m *MockgitClientInterface) ListUnstagedFiles() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUnstagedFiles")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUnstagedFiles indicates an expected call of ListUnstagedFiles.
func (mr *MockgitClientInterfaceMockRecorder) ListUnstagedFiles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUnstagedFiles", reflect.TypeOf((*MockgitClientInterface)(nil).ListUnstagedFiles))
}
