// Code generated by MockGen. DO NOT EDIT.
// Source: extractor.go
//
// Generated by this command:
//
//	mockgen -source=extractor.go -destination=mock_extractor_test.go -package=ast Extractor
//

// Package ast is a generated GoMock package.
package ast

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExtractor is a mock of Extractor interface.
type MockExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockExtractorMockRecorder
	isgomock struct{}
}

// MockExtractorMockRecorder is the mock recorder for MockExtractor.
type MockExtractorMockRecorder struct {
	mock *MockExtractor
}

// NewMockExtractor creates a new mock instance.
func NewMockExtractor(ctrl *gomock.Controller) *MockExtractor {
	mock := &MockExtractor{ctrl: ctrl}
	mock.recorder = &MockExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtractor) EXPECT() *MockExtractorMockRecorder {
	return m.recorder
}

// ExtractDiff mocks base method.
func (m *MockExtractor) ExtractDiff(ctx context.Context, beforePath, afterPath string) (*SemanticDiff, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExtractDiff", ctx, beforePath, afterPath)
	ret0, _ := ret[0].(*SemanticDiff)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExtractDiff indicates an expected call of ExtractDiff.
func (mr *MockExtractorMockRecorder) ExtractDiff(ctx, beforePath, afterPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExtractDiff", reflect.TypeOf((*MockExtractor)(nil).ExtractDiff), ctx, beforePath, afterPath)
}

// Language mocks base method.
func (m *MockExtractor) Language() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Language")
	ret0, _ := ret[0].(string)
	return ret0
}

// Language indicates an expected call of Language.
func (mr *MockExtractorMockRecorder) Language() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Language", reflect.TypeOf((*MockExtractor)(nil).Language))
}

// SupportedExtensions mocks base method.
func (m *MockExtractor) SupportedExtensions() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SupportedExtensions")
	ret0, _ := ret[0].([]string)
	return ret0
}

// SupportedExtensions indicates an expected call of SupportedExtensions.
func (mr *MockExtractorMockRecorder) SupportedExtensions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SupportedExtensions", reflect.TypeOf((*MockExtractor)(nil).SupportedExtensions))
}
