// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -source=types.go -destination=mock_analyzer_test.go -package=dataflow Analyzer
//

// Package dataflow is a generated GoMock package.
package dataflow

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAnalyzer is a mock of Analyzer interface.
type MockAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyzerMockRecorder
	isgomock struct{}
}

// MockAnalyzerMockRecorder is the mock recorder for MockAnalyzer.
type MockAnalyzerMockRecorder struct {
	mock *MockAnalyzer
}

// NewMockAnalyzer creates a new mock instance.
func NewMockAnalyzer(ctrl *gomock.Controller) *MockAnalyzer {
	mock := &MockAnalyzer{ctrl: ctrl}
	mock.recorder = &MockAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyzer) EXPECT() *MockAnalyzerMockRecorder {
	return m.recorder
}

// Analyze mocks base method.
func (m *MockAnalyzer) Analyze(files []string) (*FlowAnalysis, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analyze", files)
	ret0, _ := ret[0].(*FlowAnalysis)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Analyze indicates an expected call of Analyze.
func (mr *MockAnalyzerMockRecorder) Analyze(files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analyze", reflect.TypeOf((*MockAnalyzer)(nil).Analyze), files)
}

// DetectNilSources mocks base method.
func (m *MockAnalyzer) DetectNilSources(files []string) ([]NilSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectNilSources", files)
	ret0, _ := ret[0].([]NilSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetectNilSources indicates an expected call of DetectNilSources.
func (mr *MockAnalyzerMockRecorder) DetectNilSources(files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectNilSources", reflect.TypeOf((*MockAnalyzer)(nil).DetectNilSources), files)
}

// DetectSinks mocks base method.
func (m *MockAnalyzer) DetectSinks(files []string) ([]Sink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectSinks", files)
	ret0, _ := ret[0].([]Sink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetectSinks indicates an expected call of DetectSinks.
func (mr *MockAnalyzerMockRecorder) DetectSinks(files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectSinks", reflect.TypeOf((*MockAnalyzer)(nil).DetectSinks), files)
}

// DetectSources mocks base method.
func (m *MockAnalyzer) DetectSources(files []string) ([]Source, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectSources", files)
	ret0, _ := ret[0].([]Source)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetectSources indicates an expected call of DetectSources.
func (mr *MockAnalyzerMockRecorder) DetectSources(files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectSources", reflect.TypeOf((*MockAnalyzer)(nil).DetectSources), files)
}

// Language mocks base method.
func (m *MockAnalyzer) Language() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Language")
	ret0, _ := ret[0].(string)
	return ret0
}

// Language indicates an expected call of Language.
func (mr *MockAnalyzerMockRecorder) Language() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Language", reflect.TypeOf((*MockAnalyzer)(nil).Language))
}

// TrackFlows mocks base method.
func (m *MockAnalyzer) TrackFlows(sources []Source, sinks []Sink, files []string) ([]Flow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TrackFlows", sources, sinks, files)
	ret0, _ := ret[0].([]Flow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TrackFlows indicates an expected call of TrackFlows.
func (mr *MockAnalyzerMockRecorder) TrackFlows(sources, sinks, files any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TrackFlows", reflect.TypeOf((*MockAnalyzer)(nil).TrackFlows), sources, sinks, files)
}
